### ISSUE TITLE
Scope.cfc toStruct()  Naming Convention

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/cffractal#1]
When using the simple serializer on a collection Scope, the `toStruct()` function will return an array.   As such, it is not appropriately named.  

Suggest `getSerializedData()` or simply `serialize()` to more accurately reflect the variable typing.

**Comment by elpete** [comment]
How about `convert()` or `normalize()`?  I would like to avoid `serialize()` here since it makes me think of only the Serializer.

**Comment by jclausen** [comment]
Of the two, I'd go with "convert".  That still doesn't describe the function call, though, as well as it could.  Let me noodle on it a bit.

**Comment by elpete** [comment]
`convert()` it is!

**Comment by elpete** [comment]
Changed in [3.0.0](7f510404d43c31f8461b71897b0487a0f5f561f7)
