### ISSUE TITLE
Abstract Transformer is not singleton safe

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/cffractal#3]
If transformers are set to singletons, the retain the data from the previous usage of the transformer and unexpected data results.  An example usage of this is using the same `BaseModelTransformer` on multiple objects, with includes that use the same transformer.   The item callback provided to the top-level transformation will be passed down to all includes transformations which use the same transformer.

**Comment by jclausen** [comment]
Update: I'm not entirely convinced, now, that this is a singleton issue, but instead is an issue with recursion when using the `withItemCallback` function of the Builder

**Comment by elpete** [comment]
Fixed by #4
